name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download Downloading yolo_model_1
      run: |
        mkdir -p techtrack/storage
        wget --no-check-certificate \
          "https://www.dropbox.com/scl/fo/i4fdjtg9tigyjchjs61n0/AA2AaIy4HsoLHRkwmvVC5iU?rlkey=ke6ji9wfweorx0bd5phs2dlho&st=ixsk44d1&dl=1" \
          -O model_archive.zip
          
    - name: Extract YOLO model
      run: |
        mkdir -p techtrack/storage/yolo_model_1
        unzip model_archive.zip -d techtrack/storage/yolo_model_1 || true
        
    - name:  Download Downloading yolo_model_2
      run: |
        wget --no-check-certificate \
         "https://www.dropbox.com/scl/fo/mpqudwxmwnm2lbf8d2mo7/AOftARd-DHMPcCp800cUl3g?rlkey=3fhqixu6lalcku9o259io6b5z&st=1iiljn0i&dl=1" \
          -O model_archive_2.zip
          
    - name: Extract YOLO model
      run: |
        mkdir -p techtrack/storage/yolo_model_2
        unzip model_archive_2.zip -d techtrack/storage/yolo_model_2 || true
        
    - name: Download test videos
      run: |
        wget --no-check-certificate \
          "https://livejohnshopkins-my.sharepoint.com/:u:/g/personal/jpulido6_jh_edu/IQBJIuTDpeqiRZJvYQJxNREKAXLhjXybZNm2AKkQxC8vy6o?e=hTyM8O" \
          -O test_videos.zip

    - name: Extract test videos 
      run: |
        mkdir -p techtrack/storage/test_videos
        unzip test_videos.zip -d techtrack/storage/test_videos || true
        
    - name: Download logistics
      run: |
        wget --no-check-certificate \
          "https://livejohnshopkins-my.sharepoint.com/:u:/g/personal/jpulido6_jh_edu/IQC83xUcRiY3T5jOXuZQK__yAUXV9vahEIRIxBY8i0NKSEE?e=lZaugX" \
          -O logistics.zip
          
    - name: Extract logistics
      run: |
        mkdir -p techtrack/storage/logistics
        unzip logistics.zip -d techtrack/storage/logistics || true
        
          
    - name: Install dependencies
      run: pip install --user -r techtrack/requirements.txt
    - name: test_predict_with_empty_frame_raises_error
      id: test_predict_with_empty_frame_raises_error
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test_predict_with_empty_frame_raises_error
        command: python test/grade_runner.py test_predict_with_empty_frame_raises_error
          1
        timeout: 20
        max-score: 5
    - name: test_post_process_filters_and_converts_detections
      id: test_post_process_filters_and_converts_detections
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test_post_process_filters_and_converts_detections
        command: python test/grade_runner.py test_post_process_filters_and_converts_detections
          1
        timeout: 20
        max-score: 5
    - name: test_post_process_detection_equal_threshold
      id: test_post_process_detection_equal_threshold
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test_post_process_detection_equal_threshold
        command: python test/grade_runner.py test_post_process_detection_equal_threshold
          1
        timeout: 20
        max-score: 5
    - name: test_post_process_multiple_outputs
      id: test_post_process_multiple_outputs
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test_post_process_multiple_outputs
        command: python test/grade_runner.py test_post_process_multiple_outputs 1
        timeout: 20
        max-score: 5
    - name: test_detector_with_empty_class_file
      id: test_detector_with_empty_class_file
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test_detector_with_empty_class_file
        command: python test/grade_runner.py test_detector_with_empty_class_file 1
        timeout: 20
        max-score: 5
    - name: test_filter_with_valid_indices
      id: test_filter_with_valid_indices
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test_filter_with_valid_indices
        command: python test/grade_runner.py test_filter_with_valid_indices 1
        timeout: 20
        max-score: 5
    - name: test_filter_with_empty_indices
      id: test_filter_with_empty_indices
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test_filter_with_empty_indices
        command: python test/grade_runner.py test_filter_with_empty_indices 1
        timeout: 20
        max-score: 5
    - name: test_filter_with_single_index
      id: test_filter_with_single_index
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test_filter_with_single_index
        command: python test/grade_runner.py test_filter_with_single_index 1
        timeout: 20
        max-score: 5
    - name: test_filter_with_empty_input_lists
      id: test_filter_with_empty_input_lists
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test_filter_with_empty_input_lists
        command: python test/grade_runner.py test_filter_with_empty_input_lists 1
        timeout: 20
        max-score: 5
    - name: test_mAP_values_between_zero_and_one
      id: test_mAP_values_between_zero_and_one
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test_mAP_values_between_zero_and_one
        command: python test/grade_runner.py test_mAP_values_between_zero_and_one
          1
        timeout: 20
        max-score: 5
    - name: test_high_threshold_decrease_map_score
      id: test_high_threshold_decrease_map_score
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test_high_threshold_decrease_map_score
        command: python test/grade_runner.py test_high_threshold_decrease_map_score
          1
        timeout: 20
        max-score: 5
    - name: test_low_obj_scores
      id: test_low_obj_scores
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test_low_obj_scores
        command: python test/grade_runner.py test_low_obj_scores 1
        timeout: 20
        max-score: 5
    - name: test_duplicate_bboxes
      id: test_duplicate_bboxes
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test_duplicate_bboxes
        command: python test/grade_runner.py test_duplicate_bboxes 1
        timeout: 20
        max-score: 5
    - name: test_misclassification
      id: test_misclassification
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test_misclassification
        command: python test/grade_runner.py test_misclassification 1
        timeout: 20
        max-score: 5
    - name: test_false_negatives
      id: test_false_negatives
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test_false_negatives
        command: python test/grade_runner.py test_false_negatives 1
        timeout: 20
        max-score: 5
    - name: test_false_positives
      id: test_false_positives
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test_false_positives
        command: python test/grade_runner.py test_false_positives 1
        timeout: 20
        max-score: 5
    - name: test_get_predictions
      id: test_get_predictions
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test_get_predictions
        command: python test/grade_runner.py test_get_predictions 2
        timeout: 20
        max-score: 5
    - name: test_get_annotations
      id: test_get_annotations
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test_get_annotations
        command: python test/grade_runner.py test_get_annotations 2
        timeout: 20
        max-score: 5
    - name: test_compute_loss
      id: test_compute_loss
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test_compute_loss
        command: python test/grade_runner.py test_compute_loss 2
        timeout: 20
        max-score: 5
    - name: test_compute_loss_increases_with_lower_class_prediction
      id: test_compute_loss_increases_with_lower_class_prediction
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test_compute_loss_increases_with_lower_class_prediction
        command: python test/grade_runner.py test_compute_loss_increases_with_lower_class_prediction
          2
        timeout: 20
        max-score: 5
    - name: test_compute_loss_increases_when_objectness_decreases
      id: test_compute_loss_increases_when_objectness_decreases
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test_compute_loss_increases_when_objectness_decreases
        command: python test/grade_runner.py test_compute_loss_increases_when_objectness_decreases
          2
        timeout: 20
        max-score: 5
    - name: test_all_highly_overlapping_boxes_are_computed
      id: test_all_highly_overlapping_boxes_are_computed
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test_all_highly_overlapping_boxes_are_computed
        command: python test/grade_runner.py test_all_highly_overlapping_boxes_are_computed
          2
        timeout: 20
        max-score: 5
    - name: test_non_overlapping_boxes_do_not_contribute
      id: test_non_overlapping_boxes_do_not_contribute
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test_non_overlapping_boxes_do_not_contribute
        command: python test/grade_runner.py test_non_overlapping_boxes_do_not_contribute
          2
        timeout: 20
        max-score: 5
    - name: test_loss_increases_with_bbox_shift
      id: test_loss_increases_with_bbox_shift
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test_loss_increases_with_bbox_shift
        command: python test/grade_runner.py test_loss_increases_with_bbox_shift 2
        timeout: 20
        max-score: 5
    - name: test_loss_increases_when_true_object_objectness_is_low
      id: test_loss_increases_when_true_object_objectness_is_low
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test_loss_increases_when_true_object_objectness_is_low
        command: python test/grade_runner.py test_loss_increases_when_true_object_objectness_is_low
          2
        timeout: 20
        max-score: 5
    - name: test_false_positive_objectness_loss
      id: test_false_positive_objectness_loss
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test_false_positive_objectness_loss
        command: python test/grade_runner.py test_false_positive_objectness_loss 2
        timeout: 20
        max-score: 5
    - name: test_sample_by_total_loss
      id: test_sample_by_total_loss
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test_sample_by_total_loss
        command: python test/grade_runner.py test_sample_by_total_loss 2
        timeout: 20
        max-score: 5
    - name: test_all_loss_components_exist
      id: test_all_loss_components_exist
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test_all_loss_components_exist
        command: python test/grade_runner.py test_all_loss_components_exist 2
        timeout: 20
        max-score: 5
    - name: test_sorting_by_class_loss
      id: test_sorting_by_class_loss
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test_sorting_by_class_loss
        command: python test/grade_runner.py test_sorting_by_class_loss 2
        timeout: 20
        max-score: 5
    - name: test_equal_total_loss
      id: test_equal_total_loss
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test_equal_total_loss
        command: python test/grade_runner.py test_equal_total_loss 2
        timeout: 20
        max-score: 5
    - name: test_negative_loss_values
      id: test_negative_loss_values
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test_negative_loss_values
        command: python test/grade_runner.py test_negative_loss_values 2
        timeout: 20
        max-score: 5
    - name: test_zero_loss_values
      id: test_zero_loss_values
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test_zero_loss_values
        command: python test/grade_runner.py test_zero_loss_values 2
        timeout: 20
        max-score: 5
    - name: test_different_criteria_change_order
      id: test_different_criteria_change_order
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test_different_criteria_change_order
        command: python test/grade_runner.py test_different_criteria_change_order
          2
        timeout: 20
        max-score: 5
    - name: test_fewer_than_requested
      id: test_fewer_than_requested
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test_fewer_than_requested
        command: python test/grade_runner.py test_fewer_than_requested 2
        timeout: 20
        max-score: 5
    - name: test_invalid_column
      id: test_invalid_column
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test_invalid_column
        command: python test/grade_runner.py test_invalid_column 2
        timeout: 20
        max-score: 5
    - name: test_preserves_metadata_columns
      id: test_preserves_metadata_columns
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test_preserves_metadata_columns
        command: python test/grade_runner.py test_preserves_metadata_columns 2
        timeout: 20
        max-score: 5
    - name: test_data_types_preserved
      id: test_data_types_preserved
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test_data_types_preserved
        command: python test/grade_runner.py test_data_types_preserved 2
        timeout: 20
        max-score: 5
    - name: test_capture_video_yields_every_nth_frame_from_list
      id: test_capture_video_yields_every_nth_frame_from_list
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test_capture_video_yields_every_nth_frame_from_list
        command: python test/grade_runner.py test_capture_video_yields_every_nth_frame_from_list
          2
        timeout: 20
        max-score: 5
    - name: test_capture_video_from_directory_with_50_frames
      id: test_capture_video_from_directory_with_50_frames
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test_capture_video_from_directory_with_50_frames
        command: python test/grade_runner.py test_capture_video_from_directory_with_50_frames
          2
        timeout: 20
        max-score: 5
    - name: test_video_file_not_opened
      id: test_video_file_not_opened
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test_video_file_not_opened
        command: python test/grade_runner.py test_video_file_not_opened 2
        timeout: 20
        max-score: 5
    - name: test_detector_integration_with_storage_images
      id: test_detector_integration_with_storage_images
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test_detector_integration_with_storage_images
        command: python test/grade_runner.py test_detector_integration_with_storage_images
          2
        timeout: 20
        max-score: 5

        
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST_PREDICT_WITH_EMPTY_FRAME_RAISES_ERROR_RESULTS: ${{steps.test_predict_with_empty_frame_raises_error.outputs.result}}
        TEST_POST_PROCESS_FILTERS_AND_CONVERTS_DETECTIONS_RESULTS: ${{steps.test_post_process_filters_and_converts_detections.outputs.result}}
        TEST_POST_PROCESS_DETECTION_EQUAL_THRESHOLD_RESULTS: ${{steps.test_post_process_detection_equal_threshold.outputs.result}}
        TEST_POST_PROCESS_MULTIPLE_OUTPUTS_RESULTS: ${{steps.test_post_process_multiple_outputs.outputs.result}}
        TEST_DETECTOR_WITH_EMPTY_CLASS_FILE_RESULTS: ${{steps.test_detector_with_empty_class_file.outputs.result}}
        TEST_FILTER_WITH_VALID_INDICES_RESULTS: ${{steps.test_filter_with_valid_indices.outputs.result}}
        TEST_FILTER_WITH_EMPTY_INDICES_RESULTS: ${{steps.test_filter_with_empty_indices.outputs.result}}
        TEST_FILTER_WITH_SINGLE_INDEX_RESULTS: ${{steps.test_filter_with_single_index.outputs.result}}
        TEST_FILTER_WITH_EMPTY_INPUT_LISTS_RESULTS: ${{steps.test_filter_with_empty_input_lists.outputs.result}}
        TEST_MAP_VALUES_BETWEEN_ZERO_AND_ONE_RESULTS: ${{steps.test_mAP_values_between_zero_and_one.outputs.result}}
        TEST_HIGH_THRESHOLD_DECREASE_MAP_SCORE_RESULTS: ${{steps.test_high_threshold_decrease_map_score.outputs.result}}
        TEST_LOW_OBJ_SCORES_RESULTS: ${{steps.test_low_obj_scores.outputs.result}}
        TEST_DUPLICATE_BBOXES_RESULTS: ${{steps.test_duplicate_bboxes.outputs.result}}
        TEST_MISCLASSIFICATION_RESULTS: ${{steps.test_misclassification.outputs.result}}
        TEST_FALSE_NEGATIVES_RESULTS: ${{steps.test_false_negatives.outputs.result}}
        TEST_FALSE_POSITIVES_RESULTS: ${{steps.test_false_positives.outputs.result}}
        TEST_GET_PREDICTIONS_RESULTS: ${{steps.test_get_predictions.outputs.result}}
        TEST_GET_ANNOTATIONS_RESULTS: ${{steps.test_get_annotations.outputs.result}}
        TEST_COMPUTE_LOSS_RESULTS: ${{steps.test_compute_loss.outputs.result}}
        TEST_COMPUTE_LOSS_INCREASES_WITH_LOWER_CLASS_PREDICTION_RESULTS: ${{steps.test_compute_loss_increases_with_lower_class_prediction.outputs.result}}
        TEST_COMPUTE_LOSS_INCREASES_WHEN_OBJECTNESS_DECREASES_RESULTS: ${{steps.test_compute_loss_increases_when_objectness_decreases.outputs.result}}
        TEST_ALL_HIGHLY_OVERLAPPING_BOXES_ARE_COMPUTED_RESULTS: ${{steps.test_all_highly_overlapping_boxes_are_computed.outputs.result}}
        TEST_NON_OVERLAPPING_BOXES_DO_NOT_CONTRIBUTE_RESULTS: ${{steps.test_non_overlapping_boxes_do_not_contribute.outputs.result}}
        TEST_LOSS_INCREASES_WITH_BBOX_SHIFT_RESULTS: ${{steps.test_loss_increases_with_bbox_shift.outputs.result}}
        TEST_LOSS_INCREASES_WHEN_TRUE_OBJECT_OBJECTNESS_IS_LOW_RESULTS: ${{steps.test_loss_increases_when_true_object_objectness_is_low.outputs.result}}
        TEST_FALSE_POSITIVE_OBJECTNESS_LOSS_RESULTS: ${{steps.test_false_positive_objectness_loss.outputs.result}}
        TEST_SAMPLE_BY_TOTAL_LOSS_RESULTS: ${{steps.test_sample_by_total_loss.outputs.result}}
        TEST_ALL_LOSS_COMPONENTS_EXIST_RESULTS: ${{steps.test_all_loss_components_exist.outputs.result}}
        TEST_SORTING_BY_CLASS_LOSS_RESULTS: ${{steps.test_sorting_by_class_loss.outputs.result}}
        TEST_EQUAL_TOTAL_LOSS_RESULTS: ${{steps.test_equal_total_loss.outputs.result}}
        TEST_NEGATIVE_LOSS_VALUES_RESULTS: ${{steps.test_negative_loss_values.outputs.result}}
        TEST_ZERO_LOSS_VALUES_RESULTS: ${{steps.test_zero_loss_values.outputs.result}}
        TEST_DIFFERENT_CRITERIA_CHANGE_ORDER_RESULTS: ${{steps.test_different_criteria_change_order.outputs.result}}
        TEST_FEWER_THAN_REQUESTED_RESULTS: ${{steps.test_fewer_than_requested.outputs.result}}
        TEST_INVALID_COLUMN_RESULTS: ${{steps.test_invalid_column.outputs.result}}
        TEST_PRESERVES_METADATA_COLUMNS_RESULTS: ${{steps.test_preserves_metadata_columns.outputs.result}}
        TEST_DATA_TYPES_PRESERVED_RESULTS: ${{steps.test_data_types_preserved.outputs.result}}
        TEST_CAPTURE_VIDEO_YIELDS_EVERY_NTH_FRAME_FROM_LIST_RESULTS: ${{steps.test_capture_video_yields_every_nth_frame_from_list.outputs.result}}
        TEST_CAPTURE_VIDEO_FROM_DIRECTORY_WITH_50_FRAMES_RESULTS: ${{steps.test_capture_video_from_directory_with_50_frames.outputs.result}}
        TEST_VIDEO_FILE_NOT_OPENED_RESULTS: ${{steps.test_video_file_not_opened.outputs.result}}
        TEST_DETECTOR_INTEGRATION_WITH_STORAGE_IMAGES_RESULTS: ${{steps.test_detector_integration_with_storage_images.outputs.result}}
      with: 
        runners: test_predict_with_empty_frame_raises_error,
          test_post_process_filters_and_converts_detections,
          test_post_process_detection_equal_threshold,
          test_post_process_multiple_outputs,
          test_detector_with_empty_class_file,
          test_filter_with_valid_indices,
          test_filter_with_empty_indices,
          test_filter_with_single_index,
          test_filter_with_empty_input_lists,
          test_mAP_values_between_zero_and_one,
          test_high_threshold_decrease_map_score,
          test_low_obj_scores,
          test_duplicate_bboxes,
          test_misclassification,
          test_false_negatives,
          test_false_positives,
          test_get_predictions,
          test_get_annotations,
          test_compute_loss,
          test_compute_loss_increases_with_lower_class_prediction,
          test_compute_loss_increases_when_objectness_decreases,
          test_all_highly_overlapping_boxes_are_computed,
          test_non_overlapping_boxes_do_not_contribute,
          test_loss_increases_with_bbox_shift,
          test_loss_increases_when_true_object_objectness_is_low,
          test_false_positive_objectness_loss,
          test_sample_by_total_loss,
          test_all_loss_components_exist,
          test_sorting_by_class_loss,
          test_equal_total_loss,
          test_negative_loss_values,
          test_zero_loss_values,
          test_different_criteria_change_order,
          test_fewer_than_requested,
          test_invalid_column,
          test_preserves_metadata_columns,
          test_data_types_preserved,
          test_capture_video_yields_every_nth_frame_from_list,
          test_capture_video_from_directory_with_50_frames,
          test_video_file_not_opened,
          test_detector_integration_with_storage_images
